### ISSUE TITLE
[FA2]  Why use "encode_dropout_in_sign_bit" for dropout

### ISSUE THREAD

**Issue by endurehero** [Dao-AILab/flash-attention#1135]
![image](https://github.com/user-attachments/assets/386a3e64-3550-4d3f-ab08-b7ac8c8b4b77)
I've found that encode_dropout_in_sign_bit are currently used in two scenarios：
1. Return_softmax
2. Recompute of backward with convert_relu

I'm curious why not just set 0 instead of signbits?

**Comment by tridao** [comment]
It's just a trick to store both the dropout mask and the output of exponential in the same floating point number, to save register / space.
1. Return_softmax: we return 1 array that contains both the dropout mask (as sign) and the output of exponential.
2. Recompute of backward: we need both the dropout mask, and the output of exponential. Instead of storing it in 2 registers, we store in 1 register.
