### ISSUE TITLE
Questions about calculating the number of hmb accesses

### ISSUE THREAD

**Issue by uniqueness** [Dao-AILab/flash-attention#1260]
I have trouble understand why the number of hmb access is O(𝑁^2 𝑑^2 /𝑀) instead of O(𝑁^2 𝑑^2 /𝑀^2)? I thought the length of each of the two for loops is O(𝑁 𝑑 /𝑀). 

Also, for standard attention, why the number is O(𝑁 𝑑 + 𝑁^2)? M doesn't play a role here? When we do matrix multiplication, can we still read/write matrices in blocks of size M?

I appreciate it if someone can answer.

**Comment by tridao** [comment]
The proof is in appendix C of the FlashAttention paper.

**Comment by uniqueness** [comment]
I saw appendix C but I didn't find relevant details. Can you help?

![image](https://github.com/user-attachments/assets/149cdd1d-daf6-42c9-85c5-7f41288ac147)
Why is it NdT_c instead of T_rT_c?

![image](https://github.com/user-attachments/assets/76e4464a-684f-440f-b148-d2a351075af5)Why doesn't M play a role here?

**Comment by tridao** [comment]
There are T_c outer iterations, each iteration loading the whole Q from HBM -> SRAM, so each iteration needs O(Nd) (since there are T_r inner iteration, each loading a block of Q of size B_r * d, totaling Nd).

No M doesn't affect the IO of standard attention. Simplest analogy: if you want to do ReLU on a vector `x` of size N by operating on blocks of size M, the total IO is still N reads and N writes.

**Comment by uniqueness** [comment]
Sorry, I still miss something basic here.

"if you want to do ReLU on a vector x of size N by operating on blocks of size M", why isn't the number of HBM access N/M?

**Comment by tridao** [comment]
We're counting the number of elements, e.g. how many bytes.
