### ISSUE TITLE
CUDA Error on H100 for fmha_fwd_launch

### ISSUE THREAD

**Issue by yeeyangtee** [Dao-AILab/flash-attention#285]
**Hardware**
H100 80GB PCIE

**Key Packages**
torch==2.0.0+cu118
xformers==0.0.20
flash-attn==1.0.7

**Error Scenario**
Running sample inference code from https://github.com/damo-vilab/videocomposer
Loaded all models, latest success INFO message log was:

INFO: Successfully load step 228000 model from model_weights/non_ema_228000.pth
INFO: Created a model with 1347M parameters

Error message: `CUDA error (third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:89): no kernel image is available for execution on the device`

**Notes**
Running benchmark code below from flash-attn works fine
`PYTHONPATH=$PWD python benchmarks/benchmark_flash_attention.py`

**Comment by tridao** [comment]
If the benchmark code works then idk how it would error later on.
It's possible you need to recompile FlashAttention on your H100.

**Comment by yeeyangtee** [comment]
Hi @tridao , thanks for the quick response, really appreciate it.
I tried to recompile FlashAttention, however the same issue occurs.

Is there any additional information I could provide to help work on this issue?

**Comment by tridao** [comment]
It's possible that `python benchmarks/benchmark_flash_attention.py` is running in a different environment (or different version of Python) to your training job that errored.
Other than that I can't think of anything else.

We recommend the [Pytorch](https://catalog.ngc.nvidia.com/orgs/nvidia/containers/pytorch) container from Nvidia, which has all the required tools to install FlashAttention.

**Comment by Maxlinn** [comment]
i come across the same problem while using flash-attn, with my own model training, using nvidia h100 cards. 
already tried to compile with `python setup.py install` and it throws no errror, but still raises the same problem while training.

specs:
- nvidia h100 80G x8
- cuda 11.8
- torch 2.0.2
- flash_attn 1.0.7
- xformers 0.0.20

error:
```
CUDA error (third_party/flash-attention/csrc/flash_attn/src/fmha_fwd_launch_template.h:89): no kernel image is available for execution on the device
```

**Comment by Maxlinn** [comment]
i suspect it is because my cuda toolkit version(11.8) is too low for h100 cards, so i upgraded cuda toolkit version to 12.0. however, 

pytorch does not have a version for cuda 12.0 yet. pytorch builds for cu118 does work well with cuda toolkit 12.0 installed, but when compiling flash attention with `python3 setup.py install`, it fails to pass the version check 
```
    raise RuntimeError(CUDA_MISMATCH_MESSAGE.format(cuda_str_version, torch.version.cuda))
RuntimeError: 
The detected CUDA version (12.0) mismatches the version that was used to compile
PyTorch (11.8). Please make sure to use the same CUDA versions.
```

i'm out of solutions now. the suspious code snippet is (between two FMHA_CHECK_CUDA calls). i cannot fix it myself.

```
...
        if( smem_size >= 48 * 1024 ) {
            FMHA_CHECK_CUDA(cudaFuncSetAttribute(
                kernel, cudaFuncAttributeMaxDynamicSharedMemorySize, smem_size));
        }
        // Automatically set num_splits to maximize occupancy
        if (launch_params.params.num_splits <= 0) {
            int ctas_per_sm;
            cudaError status_ = cudaOccupancyMaxActiveBlocksPerMultiprocessor(
                &ctas_per_sm, kernel, Kernel_traits::THREADS, smem_size);
            auto dprops = at::cuda::getCurrentDeviceProperties();
            // printf("CTAS_PER_SM = %d, nSMs = %d\n", ctas_per_sm, dprops->multiProcessorCount);
            constexpr int M = Kernel_traits::Cta_tile_p::M;
            launch_params.params.num_splits = num_splits_heuristic_fwd(
                launch_params.params.b * launch_params.params.h, dprops->multiProcessorCount,
                ctas_per_sm,
                /*max_splits=*/std::min(30, (launch_params.params.seqlen_q + M - 1 / M))
            );
        }
        // printf("smem_size = %d\n", smem_size);
        dim3 grid(launch_params.params.b, launch_params.params.h, launch_params.params.num_splits);
        kernel<<<grid, Kernel_traits::THREADS, smem_size, launch_params.stream>>>(
            launch_params.params);
        FMHA_CHECK_CUDA(cudaPeekAtLastError());
    }));
}
```

i wonder if there is successful case where someone uses flash attention with h100 cards, i will be much grateful if the specs or methods can be shared.

**Comment by tridao** [comment]
It does work on H100 with the nvidia pytorch docker container.

**Comment by Maxlinn** [comment]
> It does work on H100 with the nvidia pytorch docker container.

much thank the shared information, i'll try it out soon!

**Comment by Maxlinn** [comment]
for those may concerned, if you are using xformers(flash attention is used inside xformers), just build xformers from scratch following the steps on their README. it works. do not use wheels from pip.

pytorch for now is build with cu118, which means even if your driver is using cuda 12.0 or higher, you need to install cuda 11.8 and specify it by setting env CUDA_HOME prepended to the build command. because building torch extension needs the version to be exactly the same with that torch was build.
