### ISSUE TITLE
Some thoughts about the algorithm to add bias (alibi) for bloom model

### ISSUE THREAD

**Issue by tiandiao123** [Dao-AILab/flash-attention#368]
Hello friends:
    I am wondering in order to add bias for flash-attention-2 algorithm to make it work for bloom model. I am wondering, the only thing we need to do is that we can simply add that bias matrix in line-8? If it it so, I probably can help to work on this. 
    Some one knows whether it is right? 

![image](https://github.com/Dao-AILab/flash-attention/assets/13476756/1de3e0b0-8348-49b5-b15d-22255d84bd92)

**Comment by tridao** [comment]
Conceptually it's just adding a bias vector or bias matrix to line 8. However, for the implementation, we need to take into account the "layout": each thread holds some values of S in some "permuted layout" since S is the output of an `mma` instruction (to use the Tensor Cores). For example, thread 0 holds value at indices (0, 0), (1, 0), (0, 8), (1, 8), etc. So each thread needs to read the bias at the right location.

You can read more about this "permuted layout" here:
https://github.com/NVIDIA/cutlass/blob/main/media/docs/implicit_gemm_convolution.md

**Comment by tiandiao123** [comment]
> Conceptually it's just adding a bias vector or bias matrix to line 8. However, for the implementation, we need to take into account the "layout": each thread holds some values of S in some "permuted layout" since S is the output of an `mma` instruction (to use the Tensor Cores). For example, thread 0 holds value at indices (0, 0), (1, 0), (0, 8), (1, 8), etc. So each thread needs to read the bias at the right location.
>

**Comment by tiandiao123** [comment]
> Conceptually it's just adding a bias vector or bias matrix to line 8. However, for the implementation, we need to take into account the "layout": each thread holds some values of S in some "permuted layout" since S is the output of an `mma` instruction (to use the Tensor Cores). For example, thread 0 holds value at indices (0, 0), (1, 0), (0, 8), (1, 8), etc. So each thread needs to read the bias at the right location.
> 
> You can read more about this "permuted layout" here: https://github.com/NVIDIA/cutlass/blob/main/media/docs/implicit_gemm_convolution.md

sure! Thank you! I will check it.

**Comment by tridao** [comment]
Alibi is supported in FlashAttention as of v2.4.0
