### ISSUE TITLE
Does Flash Attention2 only work with cutlass 3.0?

### ISSUE THREAD

**Issue by yumesann** [Dao-AILab/flash-attention#440]
I find that cutlass 3.1 doesn't work. There will be errors in this issue #428

**Comment by tridao** [comment]
I tried compiling with cutlass 3.1 and it didn't work, but I didn't have time to look further. Cutlass 3.2 is out now and we'll eventually switch to this newer version because of Windows support. I'll try to find time after I'm done with the current priorities (e.g. building wheels to make it easier to install, and deterministic backward pass).

**Comment by tridao** [comment]
We've just switched to cutlass 3.1.

**Comment by tmm1** [comment]
FYI cutlass 3.2 https://github.com/NVIDIA/cutlass/pull/1024/files

**Comment by tridao** [comment]
I've made changes so that the code works with Cutlass 3.2 as well. We'll switch to cutlass 3.2 once it's officially out (i.e. with a tag v3.2.0 on the cutlass repo).
