### ISSUE TITLE
Some questions about long sequence

### ISSUE THREAD

**Issue by yingtongxiong** [Dao-AILab/flash-attention#573]
Hello, I conduct some experiments about long sequence in flash2.0 in A800. I found that when I increase the sequence length to 64k, the tflops is up to 322 which is beyond the peak tflops of A800.  And our tflops is computed according to the megatron equation. And I notice that the seq len is up to 16k in the flash2.0 paper. Therefore, I want to know if there is any wrong or unsopport in flash2.0 for 64k or longer sequence? By the way, our experiment is conducted in 32 A800 and our model size is 65B. Look forward your reply. Thank you.

**Comment by tridao** [comment]
As we mentioned in Section 4.2 of the technical [report](https://arxiv.org/abs/2307.08691), the standard FLOPs formula over-counts the attention FLOPs. Due to causal masking, technically we only need to compute approximately half the number of entries in the attention matrix.
However, for consistency with previous work, we use that same FLOP formula.

**Comment by yingtongxiong** [comment]
Okay， thank you very much
