### ISSUE TITLE
[question] What dose the MP mean in MP=4?

### ISSUE THREAD

**Issue by foricee** [Dao-AILab/flash-attention#690]
In this blog https://pytorch.org/blog/flash-decoding/
What dose the MP mean in the picture title?
![image](https://github.com/Dao-AILab/flash-attention/assets/1073188/d92b65e5-e272-4ade-8fcb-1fb7fffb7e69)

**Comment by foricee** [comment]
@tridao I have a question about the picture below. When B=256, Flash-Attention v2.0.9 should have B*num_heads blocks which is larger than SM count. In this setting, Why is it still slower than Flash-Decoding?
![image](https://github.com/Dao-AILab/flash-attention/assets/1073188/658b3880-2842-4ee0-a6e4-1ed5dc0e13c9)

**Comment by tridao** [comment]
Great observation!
It's because of MQA/GQA. Let's say you have 64 query heads and 8 KV heads. Then 8 query heads attend to the same KV head. So we can treat those 8 queries as if they're from the same sequence, load that KV head once and multiply with those 8 queries. Instead of having to load that KV head 8 times to multiply by each of the 8 queries.
This optimization (credit to Daniel Haziza) was implemented in FlashAttention 2.2 (and hence FlashDecoding has it but Flash-Attention 2.0.9 doesnt).

**Comment by foricee** [comment]
Got it! you are very helpfull!
