### ISSUE TITLE
why the kBlockM in decoding-split phase must be 64?

### ISSUE THREAD

**Issue by stormytrail** [Dao-AILab/flash-attention#743]
the kBlockM set to 64 by force in split phase?
Does it decided by the TiledMma in cute?
Will it lead to extra compute when the seqlen_q = 1?

**Comment by stormytrail** [comment]
btw, I tried to set some other values for kBlockM,like 1 8 16 32, but the compiling failed, and the logs are about cute gemm
![image](https://github.com/Dao-AILab/flash-attention/assets/66992889/a5bfadc1-cfd7-43d9-a2be-6eb275cf930f)

**Comment by tridao** [comment]
Yes it's hard coded to be 64 for split case. Will lead to extra compute when seqlen_q = 1 but most of the time it doesn't matter since the operation is bounded by loading KV cache. You should benchmark.
The reason for 64 is that we have 4 warps and each warp need to handle a block of size at least 16 (because of tensor cores).

**Comment by stormytrail** [comment]
Thanks a lot!(This project is really a great job!!!)
