### ISSUE TITLE
You can't just make -j with no number

### ISSUE THREAD

**Issue by Ichimikichiki** [Dao-AILab/flash-attention#803]
On my latest XEON beast of a workstation (yes the one that holds the current benchmark world record) with 256GB of RAM I was easily pushed to exhaustion causing a whole system crash.

This is completely reckless and irresponsible. You cannot run 3000 jobs in parrallel all at once..... You are benchmarking everything at once lol. In parallel. Absolutely ridiculous.

You are the reason XFORMERS causes everyone's system to crash every time someone tries to build it from source.
By way of DOSing their system.

Follow industry standards and limit the number of jobs to the number of cores on the system.

Just to make it clear..... -j by itself makes the number whatever the total number of tasks that has to be completed. So that could be 3000, or 10000 or whatever. I highly doubt you would ever `make -j3000` in most situations.

**Comment by tridao** [comment]
Do you want to send a PR?

**Comment by Qubitium** [comment]
This is partially fixed by https://github.com/Dao-AILab/flash-attention/pull/832 by assinging MAX_JOBS to a number tailed to the actual env and not just blanket all cpu cores. 

@Ichimikichiki  But the underlying problem is speed of compile vs the so called ddos, which is not accurate, since you are installing the package and the package install is using lots of cpu/ram resources which actually normal for flash-attn.  I know it's strange for a pkg to use literally all cpu cores and ram but flash-attn is what it is so work with the beast rather then against it. Use my PR which still try to use close to 100% plus utilization (but still affect service quality if this is on a server with other tenants)  or weigh cost-benefit of faster install vs less resource usage by manually setting MAX_JOBS env var.

**Comment by Ichimikichiki** [comment]
You are wrong. The build uses up 100% of each CPU cycle. You cannot even run hyperthreading or it will just lock.
