### ISSUE TITLE
Headdim=512 seems to work with simple modifications. Should Headdim=1024 work?

### ISSUE THREAD

**Issue by scott-intense** [Dao-AILab/flash-attention#805]
I've made naive modifications to enable headdim=512. The entailed adding a `run_mha_fwd_hdim512`, `run_mha_fwd_<cutlass::half_t, 512>` (and bf16 so things compile but i'm not using it.)  Fwd, at least, seems to work. It runs and output appears to be correct. The "meat" of the modification is in `run_mha_fwd_hdim512`:

`run_flash_fwd<Flash_fwd_kernel_traits<Headdim, 64, 32, 4, false, false, T>, Is_dropout, Is_causal>(params, stream);`

Similar modifications to enable headdim=1024 do not work. The kernel runs and appears to generate some results, but they seem to be incorrect. This is using the same straightforward modification above. Any advice on how to debug/proceed would be greatly appreciated!

**Comment by tridao** [comment]
Are there models with headdim 512 or 1024? 
With such large headdim (1024) it's likely faster to use the naive attn calculation rather than flash-attn.
With headdim 1024, block size = 32, we'd need to load in Q, K, V of size 32 x 1024 to shared memory, with fp16/bf16 that's 196KB. More than what A100 has (only 163KB per thread block). I'm surprised it runs at all.

**Comment by scott-intense** [comment]
Thanks for the response! Yes, there are models using 512 and 1024. Sounds like headdim=1024 might run on H100. I can give that a go. I'll also look at naive (and memeff?)

Thanks again!
