### ISSUE TITLE
"flash_attn" cannot be installed on the A800 graphics card？

### ISSUE THREAD

**Issue by GXKIM** [Dao-AILab/flash-attention#806]
I believe it should be possible, but currently, I'm unable to install it.

cu:12.1
torch: 2.1

**Comment by tridao** [comment]
I also believe it's possible

**Comment by userdsr** [comment]
I failed to install flas-attn on A800, I tried many times.

**Comment by Qubitium** [comment]
A800 should work. Please provide install errors and stacktraces so we can further debug this.  

Though I highly suspect the install errors are just `setup.py ` crashing due to oom which my PR should solve: https://github.com/Dao-AILab/flash-attention/pull/832 Try it out and see if it resolves your install errors. @userdsr  @GXKIM
