### ISSUE TITLE
Why is paged attention faster than its non-paged counterpart?

### ISSUE THREAD

**Issue by ramyaprabhu-alt** [Dao-AILab/flash-attention#841]
Hi,
I was benchmarking paged attention which was recently added to flash_attn_with_kvcache.
I based my benchmarking script entirely on the test function that is in test_flash_attn.py file.
For MHA, I see the following:

| bs | seqlen | flash_duration_nonpaged | flash_duration_paged | nonpaged/paged |
| -- | -------- | --------------------------- | ------------------------ | -------------------- | 
| 32.0 | 1024.0 | 0.37 | 0.344 | 1.0755813953488373 |
| 32.0 | 2048.0 | 0.719 | 0.668 | 1.0763473053892214 |
| 32.0 | 4096.0 | 1.728 | 1.309 | 1.3200916730328496 |
| 32.0 | 8192.0 | 3.522 | 2.616 | 1.3463302752293578 |
| 32.0 | 16384.0 | 6.953 | 5.548 | 1.2532444124008653 |
| 32.0 | 32768.0 | 14.969 | 0.0 | inf |
| 32.0 | 65536.0 | 0.0 | 0.0 | inf |

in some cases I see paged attention being 34% faster than its non-paged counter part. My understanding is that paged attention should ideally always take more time. Any idea why this is happening? @tridao @beginlner

**Comment by tridao** [comment]
Seems strange, do you have a short script to reproduce?

**Comment by ramyaprabhu-alt** [comment]
[flash_microbenchmark_pgdvsnnpgd.txt](https://github.com/Dao-AILab/flash-attention/files/14354529/flash_microbenchmark_pgdvsnnpgd.txt)   -> python script I used for benchmarking

**Comment by beginlner** [comment]
I noticed that and found it strange before as well.

**Comment by tridao** [comment]
There are 2 implementations: "non-split" and "split" (i.e. flash-decoding). There's a heuristic to pick which implementation to run. 
For your case the non-paged KV runs the "non-split" implementation, which uses a block size of 128 (for q) x 64 (for k/v). This is great for large seqlen_q (e.g. training) but if seqlen_q = 1 it's wasteful.
The paged KV runs the "split" implementation (since only "split" implementation supports paged KV). This uses block size of 64 (for q) x 128 (for k/v), so loading KV cache is sightly faster here.

If you set new_kv = True, or if there's rotary, then both paged and non-paged KV will trigger the "split" implementation. You can try that.

**Comment by ramyaprabhu-alt** [comment]
Hey, your suggestion worked. Thank you!
